package com.cft.hogan.platform.ppm.api.util;

public abstract class SqlQueries {

	/*
	 * PPM_MM_IMPORT_TASK
	 */
	
	public static final String PPM_MM_IMPORT_TASK_FIND_BY_UUID = "SELECT * FROM CELPPM.PPM_MM_IMPORT_TASK WHERE UUID = ?";

	public static final String PPM_MM_IMPORT_TASK_FIND_BY_STATUS = "SELECT * FROM CELPPM.PPM_MM_IMPORT_TASK WHERE STATUS = ? ORDER BY MODIFIED_TS DESC";

	public static final String PPM_MM_IMPORT_TASK_UPDATE_BY_STATUS = "UPDATE CELPPM.PPM_MM_IMPORT_TASK SET STATUS = ? , MODIFIED_BY = ? , MODIFIED_TS = ? WHERE UUID = ?";

	public static final String PPM_MM_IMPORT_TASK_SAVE = "INSERT INTO CELPPM.PPM_MM_IMPORT_TASK (UUID, TYPE, NAME, STATUS, INPUT_FILE_NAME, CREATED_BY, CREATED_TS , MODIFIED_BY, MODIFIED_TS) "
			+ "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String PPM_MM_IMPORT_TASK_DELETE = "DELETE FROM CELPPM.PPM_MM_IMPORT_TASK WHERE UUID = ?";
	
	
	/*
	 * PPM_MM_IMPORT_TASK_DETAILS
	 */

	public static final String PPM_MM_IMPORT_TASK_DETAILS_FIND_BY_UUID = "SELECT * FROM CELPPM.PPM_MM_IMPORT_TASK_DETAILS WHERE IM_TASK_UUID = ? ORDER BY MODIFIED_TS DESC";
	
	public static final String PPM_MM_IMPORT_TASK_DETAILS_FIND_BY_UUID_AND_STATUS = "SELECT * FROM CELPPM.PPM_MM_IMPORT_TASK_DETAILS WHERE IM_TASK_UUID = ? AND STATUS = ? ORDER BY MODIFIED_TS DESC";
	
	public static final String PPM_MM_IMPORT_TASK_DETAILS_UPDATE = "UPDATE CELPPM.PPM_MM_IMPORT_TASK_DETAILS SET "
	+ "ACTION = ? , STATUS = ? , RESULT = ? , COMPANY_ID = ? , APPLICATION_ID = ? "
	+ "WHERE IM_TASK_UUID = ? AND PSET_KEY = ?";
	
	
	/*
	 * PPM_MM_SCHEDULED_TASK
	 */
	
	public static final String PPM_MM_SCHEDULED_TASK_FIND_BY_UUID = "SELECT * FROM CELPPM.PPM_MM_SCHEDULED_TASK " +
	"WHERE UUID = ?";
	
	public static final String PPM_MM_SCHEDULED_TASK_FIND_BY_TEMPLATE_UUID = "SELECT * FROM CELPPM.PPM_MM_SCHEDULED_TASK " +
	"WHERE TEMPLATE_UUID = ?";
	
	public static final String PPM_MM_SCHEDULED_TASK_FIND_BY_TYPE = "SELECT * FROM CELPPM.PPM_MM_SCHEDULED_TASK " +
	"WHERE type = ?  ORDER BY MODIFIED_TS DESC";
	
	public static final String PPM_MM_SCHEDULED_TASK_FIND_BY_STATUS = "SELECT * FROM CELPPM.PPM_MM_SCHEDULED_TASK " +
	"WHERE STATUS = ? AND EFF_DATE <= ? AND TYPE = ?  ORDER BY MODIFIED_TS DESC";
	
	public static final String PPM_MM_SCHEDULED_TASK_INSERT = "INSERT INTO CELPPM.PPM_MM_SCHEDULED_TASK " +
	"(UUID, TEMPLATE_UUID, NAME, TYPE, EFF_DATE, FILE_PATH, FREQUENCY, FREQ_PATTERN, TASK_OPTIONS, STATUS, REMARKS, CREATED_BY, CREATED_TS, MODIFIED_BY, MODIFIED_TS) "+
	"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String PPM_MM_SCHEDULED_TASK_UPDATE = "UPDATE CELPPM.PPM_MM_SCHEDULED_TASK SET " +
	"TEMPLATE_UUID = ? , NAME = ? , EFF_DATE = ? , FILE_PATH = ? , FREQUENCY = ? , FREQ_PATTERN = ? , TASK_OPTIONS = ? , STATUS = ? , REMARKS = ? , MODIFIED_BY = ? , MODIFIED_TS = ? "+
	"WHERE UUID = ?";
	
	public static final String PPM_MM_SCHEDULED_TASK_DELETE = "DELETE FROM CELPPM.PPM_MM_SCHEDULED_TASK " +
	"WHERE UUID = ?";
	
	/*
	 * PPM_MM_TEMPLATE
	 */
	
	public static final String PPM_MM_TEMPLATE_FIND_BY_UUID = "SELECT * FROM CELPPM.PPM_MM_TEMPLATE " +
	"WHERE UUID = ?";
	
	public static final String PPM_MM_TEMPLATE_FIND_ALL = "SELECT * FROM CELPPM.PPM_MM_TEMPLATE ORDER BY MODIFIED_TS DESC";
	
	public static final String PPM_MM_TEMPLATE_INSERT = "INSERT INTO CELPPM.PPM_MM_TEMPLATE " +
	"(UUID, NAME, CREATED_BY, CREATED_TS, MODIFIED_BY, MODIFIED_TS) "+
	"VALUES (?, ?, ?, ?, ?, ?)";
	
	public static final String PPM_MM_TEMPLATE_UPDATE = "UPDATE CELPPM.PPM_MM_TEMPLATE SET " +
	"MODIFIED_BY = ? , MODIFIED_TS = ? "+
	"WHERE UUID = ?";
	
	public static final String PPM_MM_TEMPLATE_DELETE = "DELETE FROM CELPPM.PPM_MM_TEMPLATE " +
	"WHERE UUID = ?";
	
	/*
	 * PPM_MM_TEMPLATE_PSET
	 */
	
	public static final String PPM_MM_TEMPLATE_PSET_FIND_BY_TEMPLATE_UUID = "SELECT * FROM CELPPM.PPM_MM_TEMPLATE_PSET " +
	"WHERE TEMPLATE_UUID = ?  ORDER BY NUMBER";
	
	public static final String PPM_MM_TEMPLATE_PSET_INSERT_WITH_EFF_DATE = "INSERT INTO CELPPM.PPM_MM_TEMPLATE_PSET " +
	"(UUID, TEMPLATE_UUID, NUMBER, NAME, COMPANY_ID, APPLICATION_ID, CREATED_BY, CREATED_TS, MODIFIED_BY, MODIFIED_TS, EFF_DATE) "+
	"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String PPM_MM_TEMPLATE_PSET_INSERT_WITHOUT_EFF_DATE = "INSERT INTO CELPPM.PPM_MM_TEMPLATE_PSET " +
	"(UUID, TEMPLATE_UUID, NUMBER, NAME, COMPANY_ID, APPLICATION_ID, CREATED_BY, CREATED_TS, MODIFIED_BY, MODIFIED_TS) "+
	"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String PPM_MM_TEMPLATE_PSET_DELETE = "DELETE FROM CELPPM.PPM_MM_TEMPLATE_PSET " +
	"WHERE TEMPLATE_UUID = ?";
}
